#!/bin/bash
#global path to database directory
DB_DIR="/home/hoda/Documents/Bash/Bash Project/Database/"


navigate_menu() {
    echo ">>Do you want to go back to the main menu? (yes/no)"
    read user_choice
    if [[ "yes"  =~ "$user_choice" ]]; then
         ./MainMenu
    elif [[ "no"  =~ "$user_choice"  ]]; then
        echo "Exiting. Goodbye!"
        exit 0
    else
        echo "Invalid option! Please try again."
        navigate_menu
    fi
}