#!/bin/bash
source ./Common
source ./TablesMenu

function connectDB(){
  echo -e "${cyan}>> Enter database name you want to connect: ${clear}" 
  ls "$DB_DIR" 
  read connDB

 if [ -e "$DB_DIR/$connDB" ];
 then
   cd "$DB_DIR/$connDB"
   echo "$connDB is selected"
   echo "Current directory: $(pwd)" 
   Ps1="$DB_DIR/$connDB"
   SelectDB="$connDB"
   #tables menu 
   tablesMenu
 else
   echo "DB is not selected"
 fi
 #navigate_menu
}