#!/bin/bash
source ./Validations
source ./Common

flag=1

function create_database() {
  
    echo ">>Enter the name of the database you want to create:--------"
    read dbName
    #checking validations
    if ! is_empty_input "$dbName" && ! is_already_exists_dir "$dbName" && ! is_invalid_name "$dbName"; then
        echo "Processing...."
        sleep 0.5
        echo "Database name '$dbName' is valid."
        flag=1
    else
        flag=0
        create_database
    fi

    if [ "$flag" -eq 1 ]; then
        if mkdir "$DB_DIR/$dbName"; then
            echo "---------Database '$dbName' created successfully----------"
        else
            echo "Could not create database '$dbName'."
        fi
    fi
    navigate_menu
}