#!/bin/bash
source ./Validations
source ./Common

#declare flag variable to check sucess of operations
flag=1

function create_table() {
    read -p ">>Enter table name: " tblName
    if ! is_empty_input "$tblName" && ! is_already_exists_file "$tblName" && ! is_invalid_name "$tblName" ; then
        echo "Table name '$tblName' is valid------------------"
        echo "Continuing---------------------------------------"
        flag=1
    else
        flag=0
        create_table
    fi

    if [ $flag -eq 1 ]; then
        # Input number of columns-------------------------------
        read -p ">>Enter the number of columns in your table: " colNum

        if ! is_empty_input $colNum && ! is_less_than_zero $colNum; then
            echo "files '$tblName' , '$tblName'.metadata created for the table creation..."
            touch "$tblName" "$tblName.metadata"

            echo "Number of columns '$colNum' is valid."
            echo "Continuing-----------------------------------"
            sleep 0.5
            flag=1
            create_columns
        else
            echo "Failed validation checks......."
            flag=0
            create_table
        fi  
    fi
}

function create_columns() {
    #adding PK column
    if [ $flag -eq 1 ]; then
        echo ">>Enter column name 1 (PRIMARY KEY column) followed by datatype (int/string):  eg:id int "
        read colName colType
        if ! is_empty_input "$colName" && ! is_invalid_name "$colName" &&  \
        ! is_empty_input "$colType" && ! is_invalid_datatype "$colType" && \
        ! is_duplicate_column "$colName" "$tblName.metadata" ; then
            echo "$colName:$colType:PK" >> "$tblName.metadata"
            flag=1
        else
            echo "Failed validation checks. Aborting table creation..."
            rm "$tblName" "$tblName.metadata"
            flag=0
            navigate_menu
        fi
    fi

    if [ $flag -eq 1 ]; then
    for ((i=2; i<$colNum+1; i++)) #loop through the number of columns -1 
    do
        echo ">>Enter column name $i followed by datatype (int/string):  eg: name string"
        read colName colType
        if ! is_empty_input "$colName" && ! is_invalid_name "$colName" &&  \
        ! is_empty_input "$colType" && ! is_invalid_datatype "$colType" && \
        ! is_duplicate_column "$colName" "$tblName.metadata" ; then
            echo "$colName:$colType" >> "$tblName.metadata"
            flag=1
        else
            echo "Failed validation checks. Aborting table creation..."
            rm "$tblName" "$tblName.metadata"
            navigate_menu
        fi
    done
    fi
    if [ $flag -eq 1 ]; then
        echo "Table '$tblName' created successfully."
        navigate_menu
    fi
}
    

#temp code for testing .. delete later
cd Database/DB1
create_table
