#!/bin/bash
source ./Validations
source ./Common

flag=1

function create_database() {
    echo -e ${cyan}">>Enter the name of the database you want to create: ${clear}"
    read dbName
    #checking validations
    if ! is_empty_input "$dbName" && ! is_already_exists_dir "$dbName" &&  is_valid_name "$dbName"; then
        echo -e "${blue}Processing...."
        sleep 0.5
        echo -e "Database name ${magenta}[ $dbName ]${blue} is valid to create.${clear}"
        flag=1
    else
        flag=0
        create_database
    fi

    if [ "$flag" -eq 1 ]; then
        if mkdir "$DB_DIR/$dbName"; then
            echo -e ${green}"---------DATABASE ${magenta}[ $dbName ]${green} CREATED SUCCESSFULLY----------"
            DATABASES_ARR+=("$dbName")
        else
            echo -e ${red}"Could not create database '$dbName'."
        fi
    fi
    navigate_menu
}