#!/bin/bash
dropDatabase(){
read -p "Enter database name you want to drop: " dropdb
 if [ -e "$DB_DIR/$dropdb" ]
 then
   rm -r "$DB_DIR/$dropdb"
   echo "$dropdb is dropped"
 else
   echo "DB is not exist"
 fi
 navigate_menu
}