#!/bin/bash
source ./Validations
source ./Common

function list_database() {
    echo "The following databases exist:-------------------------------------------------- "
    #Lists directories in $DB_DIR and removes the trailing slashes from the directory names.
    ls -F "$DB_DIR" | grep / | tr -d "/"

    navigate_menu
}