#!/bin/bash
source ./CreateDatabase
source ./ConnectDatabase 
source ./DropDatabase
source ./ListDatabase 
source ./Validations

function main_menu() {
    #check if the directory exists
    if ! is_already_exists_db_dir "$DB_DIR" ;then
        mkdir -p "$DB_DIR"
    fi

    echo -e "${magenta}-- -- -- -- Welcome to the Database Management System -- -- -- --${clear}"
    PS3=$(echo -e "${cyan}>> Choose an option: ${clear}") # Colorize the prompt

    select option in "Create Database"  "List Database"   "Connect Database" "Drop Database"  "Exit"; do
        case $option in
            "Create Database")
                create_database # Call the function from CreateDatabase
                ;;
            "List Database")
                list_database  # Call the function from ListDatabase
                ;;
            "Connect Database")
                connect_to_database  
                break  
                ;;
            "Drop Database")
                drop_database  # Call the function from DropDatabase
                break
                ;;
            "Exit")
                echo -e "${blue}Exiting. Goodbye!${clear}"
                exit 0  # Exit the script
                ;;
            *)
                echo -e "${yellow}Warning: Invalid option. Please try again.${clear}" 
                ;;
        esac
    done
}

navigate_menu() {
    echo -e "${gray}>>Do you want to go back to the main menu? (yes/no) ${clear}"
    read  user_choice
    if [[ "yes"  =~ "$user_choice" ]]; then
         main_menu
    elif [[ "no"  =~ "$user_choice"  ]]; then
        echo -e "${blue}Exiting. Goodbye!"
        exit 0
    else
        echo -e "${yellow} Warrning: Invalid option! Please try again. ${clear}"
        navigate_menu
    fi
}

main_menu
