#! /bin/bash
source ./TableCreate
source ./TableList
source ./TableSelect
source ./TableDrop
source ./TableInsert    
source ./TableUpdate
source ./TableDeleteFrom

function tablesMenu(){
    echo -e "${magenta}-- -- -- --Welcome to $SELECTED_DB-- -- -- --${clear}"
    PS3=$(echo -e "${cyan}>> Choose an option: ${clear}") # Colorize the prompt

    select option in "Create Table" "Insert into Table" "List Tables" "Select from Table" "Update Table" "Drop Table" "Delete from Table" "Back to Main Menu" "Exit"; do
        case $option in
            "Create Table")
                create_table
                ;;
            "Insert into Table")
                insert_into_table
                ;;
            "List Tables")
                listTables
                ;;
            "Select from Table")
                select_from_table
                ;;
            "Update Table") 
                update_table
                ;;
            "Drop Table")
                drop_table
                break
                ;;
            "Delete from Table")
                delete_from_table
                ;;
            "Back to Main Menu")
                main_menu
                ;;
            "Exit")
                echo -e "${blue}Exiting. Goodbye!${clear}"
                exit 0
                ;;
            *)
                echo -e "${yellow}Warning: Invalid option. Please try again.${clear}" 
                ;;
        esac
    done
}
