#! /bin/bash
source ./Common

function listTables(){
  #ensure user is connected to db
  if [ -z "$SELECTED_DB" ]; then
    echo -e "${yellow}Warrning: No database selected. Please connect to a database first.${clear}"
    return
  fi

  #dir containing tables
  dbDirPath="$DB_DIR/$SELECTED_DB"

  tableCount=$(find "$dbDirPath" -type f ! -name "*.metadata" | wc -l)
  if [[ "$tableCount" -eq 0 ]]; then
    echo -e "${blue}No tables found in ${SELECTED_DB} ...${clear}"
    sleep 0.5
    echo -e "${blue}Aborting Listing.${clear}"
    return
  fi
  
  echo -e "${magenta}-- -- -- --Available Tables in $SELECTED_DB-- -- -- ${clear}"
  
  for file in "$dbDirPath"/*; do
    if [[ "$file" != *.metadata ]]; then
      tableName=$(basename "$file")
      echo -e "${blue}$tableName${clear}"
    fi
  done

  tablesMenu
}