#!/bin/bash
is_empty_input() {
    if [ -z "$1" ]; then
        echo "Warning: $1 cannot be empty."
        return 0
    else
        return 1
    fi
}

is_already_exists_dir() {
    if [ -d "$1" ]; then
        echo "Warning: $1 already exists."
        return 0
    else
        return 1
    fi
}
is_already_exists_file() {
    if [ -f "$1" ]; then
        echo "Warning: $1 already exists."
        return 0
    else
        return 1
    fi
}

is_invalid_name() {
    if [[ ! $1 =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
        echo "Warning: Invalid name '$1'. Name must start with a letter or underscore and contain only letters, numbers, and underscores."
        return 0
    else
        return 1
    fi
}

# Function: Validate column datatype
is_invalid_datatype() {
    local validTypes=("int" "string" "float")
    if [[ ! " ${validTypes[*]} " =~ " $1 " ]]; then
        echo "Warning: Invalid datatype '$1'. Valid types are: ${validTypes[*]}"
        return 0
    else
        return 1
    fi
}

# Function: Validate unique column name
is_duplicate_column() {
    if grep -q "^$1:" "$2"; then
        echo "Warning: Column name '$1' already exists in $2."
        return 0
    else
        return 1
    fi
}

is_less_than_zero () {
    if [[ "$1" -le 0 ]]; then
        echo "Warning: Value must be bigger than zero."
        return 0
    else
        return 1
    fi
}


